#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons
source "$HOME/.config/sketchybar/fonts.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

PADDINGS=3 # All paddings use this value (icon, label, background)

BUILTIN_DISPLAY=0
# shellcheck disable=SC2034,SC2155
BUILTIN_DISPLAY="$(
  system_profiler -json SPDisplaysDataType | jq '.SPDisplaysDataType[0].spdisplays_ndrvs | map(select(.spdisplays_main == "spdisplays_yes")) | .[].spdisplays_display_type' | grep -q -v built-in-liquid-retina
  echo $?
)"

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance and default values
sketchybar --bar height=35 \
  display=main \
  color=$BAR_COLOR \
  shadow=off \
  position=top \
  sticky=on \
  padding_right=12 \
  padding_left=12 \
  corner_radius=0 \
  y_offset=0 \
  margin=0 \
  blur_radius=0 \
  notch_width=200 \
  \
  --default updates=when_shown \
  icon.font="$FONT:Bold:14.0" \
  icon.color=$ICON_COLOR \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.font="$FONT:Semibold:13.0" \
  label.color=$LABEL_COLOR \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  background.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \
  background.height=26 \
  background.corner_radius=9 \
  popup.background.border_width=2 \
  popup.background.corner_radius=11 \
  popup.background.border_color=$POPUP_BORDER_COLOR \
  popup.background.color=$POPUP_BACKGROUND_COLOR \
  popup.background.shadow.drawing=on

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
#source "$ITEM_DIR/aerospaces.sh"
source "$ITEM_DIR/front_app.sh"
# source "$ITEM_DIR/apple_music.sh"
source "$ITEM_DIR/spotify.sh"

# Center
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/linode.sh"

# Right
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/battery.sh"
# source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/divider.sh"
# source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/stats.sh"
source "$ITEM_DIR/clock.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
