[tools]
usage = "latest"
teleport-community = "14.0.3"
rye = "0.36.0"
pint = "0.61.2"
bun = "latest"
goreleaser = "latest"
just = "latest"
node = "20"
yarn = "1"
pnpm = "latest"
"go:github.com/oz/tz" = "latest"
uv = "latest"
jq = "1.6"
bat = "0.24.0"
vault = "1.13.2+ent"
terraform = "1.3.6"
flux2 = "0.38.3"
pre-commit = "3.4.0"
yq = "4.35.2"
vale = "3.0.5"
kustomize = "5.3.0"
kubectl = "1.29.1"
kubectx = "0.9.5"
age = "1.1.1"
sops = "3.8.1"
k9s = "0.32.5"
ripgrep = "14.1.0"
go = "1.23.0"
fzf = "0.55.0"
difftastic = "0.60.0"
"go:github.com/prometheus/alertmanager/cmd/amtool" = "latest"
helm = "3.13.0"
git-cliff = "2.5.0"
python = "3.11.10"
sloth = "0.12.0"
"go:github.com/neilotoole/sq" = "0.48.3"
ruff = "0.6.9"
go-jsonnet = "0.20.0"
lazygit = "0.44.1"
rust = "latest"
otelcol = "0.95.0"
act = "0.2.68"
infracost = "0.10.39"
pandoc = "latest"
chezmoi = "latest"
argocd = "2.12.2"

[settings]
experimental = true
