[tools]
usage = "latest"
bun = "latest"
goreleaser = "latest"
"go:github.com/oz/tz" = "latest"
uv = "latest"
pipx = "latest"
jq = "1.6"
bat = "0.24.0"
vault = "1.13.2+ent"
terraform = "1.3.6"
flux2 = "0.38.3"
pre-commit = "3.4.0"
yq = "4.35.2"
kustomize = "5.3.0"
kubectl = "1.29.1"
kubectx = "0.9.5"
kubens = "0.9.5"
age = "1.1.1"
sops = "3.8.1"
k9s = "latest"
ripgrep = "14.1.0"
go = "1.23"
difftastic = "latest"
helm = "3.13.0"
python = "3.11.10"
ruff = "0.6.9"
go-jsonnet = "0.20.0"
lazygit = "latest"
rust = "latest"
act = "0.2.68"
chezmoi = "latest"
starship = "1.21.1"
neovim = "0.10.2"
markdownlint-cli2 = "latest"
fd = "latest"
node = "22.6.0"
1password = "latest"
github-cli = "latest"
"pipx:ansible" = { version = "latest", uvx = "false", pipx_args = "--include-deps" }
cheat = "latest"
delta = "latest"
vale = "3.11"
"npm:prettier" = "latest"
"pipx:linode-cli" = "latest"
"cargo:trippy" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
bun = true
